import {auth,onAuthStateChanged} from "./firebase.js";
import {fetchAllTransactions,initTransactionModal,deleteTransaction,CATEGORIES} from "./transactions.js";
const money=n=>"₹"+Number(n||0).toLocaleString("en-IN",{maximumFractionDigits:2});let allTxs=[],modal;
function populateCategoryFilter(){const sel=document.getElementById("filter-category");if(sel)sel.innerHTML='<option value="all">All Categories</option>'+CATEGORIES.map(c=>`<option value="${c}">${c}</option>`).join("")}
function getFilters(){return{search:(document.getElementById("filter-search")?.value||"").toLowerCase().trim(),category:document.getElementById("filter-category")?.value||"all",type:document.getElementById("filter-type")?.value||"all",from:document.getElementById("filter-from")?.value||"",to:document.getElementById("filter-to")?.value||"",sort:document.getElementById("filter-sort")?.value||"newest"}}
function applyFilters(){const f=getFilters();let result=allTxs.filter(t=>{const d=t.date?.toDate?t.date.toDate():new Date(t.date);if(f.search&&!(`${t.description} ${t.category}`.toLowerCase().includes(f.search)))return false;if(f.category!=="all"&&t.category!==f.category)return false;if(f.type!=="all"&&t.type!==f.type)return false;if(f.from&&d<new Date(f.from))return false;if(f.to&&d>new Date(f.to+"T23:59:59"))return false;return true});result.sort((a,b)=>{const da=a.date?.toDate?a.date.toDate():new Date(a.date),db=b.date?.toDate?b.date.toDate():new Date(b.date);return f.sort==="newest"?db-da:da-db});renderTable(result)}
function renderTable(txs){const tbody=document.getElementById("tx-table-body"),empty=document.getElementById("tx-empty-state");if(!tbody)return;if(!txs.length){tbody.innerHTML="";if(empty)empty.style.display="block";return}if(empty)empty.style.display="none";tbody.innerHTML=txs.map(t=>{const d=t.date?.toDate?t.date.toDate():new Date(t.date),cls=t.type==="income"?"amount-income":"amount-expense",sign=t.type==="income"?"+":"−";return `<tr data-id="${t.id}"><td>${d.toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"})}</td><td><span class="badge badge-${t.type}">${t.type}</span></td><td>${t.category}</td><td class="tx-desc-cell">${t.description||"—"}</td><td class="${cls}">${sign} ${money(t.amount)}</td><td class="tx-actions"><button class="icon-btn" data-edit="${t.id}" title="Edit">✎</button><button class="icon-btn icon-btn-danger" data-delete="${t.id}" title="Delete">🗑</button></td></tr>`}).join("");tbody.querySelectorAll("[data-edit]").forEach(btn=>btn.addEventListener("click",()=>{const tx=allTxs.find(t=>t.id===btn.dataset.edit);if(tx&&modal)modal.open(tx)}));tbody.querySelectorAll("[data-delete]").forEach(btn=>btn.addEventListener("click",async()=>{if(!confirm("Delete this transaction? This cannot be undone."))return;await deleteTransaction(btn.dataset.delete);await refresh()}))}
async function refresh(){allTxs=await fetchAllTransactions();applyFilters()}
function wireFilterEvents(){["filter-search","filter-category","filter-type","filter-from","filter-to","filter-sort"].forEach(id=>{const el=document.getElementById(id);if(el){el.addEventListener("input",applyFilters);el.addEventListener("change",applyFilters)}});document.getElementById("filter-reset")?.addEventListener("click",()=>{document.getElementById("filter-search").value="";document.getElementById("filter-category").value="all";document.getElementById("filter-type").value="all";document.getElementById("filter-from").value="";document.getElementById("filter-to").value="";document.getElementById("filter-sort").value="newest";applyFilters()})}
onAuthStateChanged(auth,user=>{if(!user)return;populateCategoryFilter();wireFilterEvents();modal=initTransactionModal({onSaved:refresh});refresh()});