import {auth,db,collection,addDoc,updateDoc,deleteDoc,doc,getDocs,query,orderBy,serverTimestamp,Timestamp} from "./firebase.js";
const CATEGORIES=["Food","Transport","Shopping","Bills","Education","Entertainment","Health","Travel","Other"];
function txCollection(uid){return collection(db,"users",uid,"transactions")}
async function fetchAllTransactions(){const user=auth.currentUser;if(!user)return[];const snap=await getDocs(query(txCollection(user.uid),orderBy("date","desc")));return snap.docs.map(d=>({id:d.id,...d.data()}))}
async function addTransaction({type,amount,category,description,date}){const user=auth.currentUser;if(!user)throw Error("Not signed in");return addDoc(txCollection(user.uid),{type,amount:Number(amount),category,description:description||"",date:Timestamp.fromDate(new Date(date)),createdAt:serverTimestamp()})}
async function updateTransaction(txId,{type,amount,category,description,date}){const user=auth.currentUser;if(!user)throw Error("Not signed in");return updateDoc(doc(db,"users",user.uid,"transactions",txId),{type,amount:Number(amount),category,description:description||"",date:Timestamp.fromDate(new Date(date))})}
async function deleteTransaction(txId){const user=auth.currentUser;if(!user)throw Error("Not signed in");return deleteDoc(doc(db,"users",user.uid,"transactions",txId))}
function buildModalMarkup(){const options=CATEGORIES.map(c=>`<option value="${c}">${c}</option>`).join("");return `<div class="modal-overlay" id="tx-modal-overlay"><div class="modal" role="dialog" aria-modal="true"><div class="modal-header"><h3 id="tx-modal-title">Add Transaction</h3><button class="modal-close" id="tx-modal-close" aria-label="Close">&times;</button></div><form id="tx-form"><input type="hidden" id="tx-id"/><div class="type-toggle"><button type="button" class="type-btn active" data-type="expense">Expense</button><button type="button" class="type-btn" data-type="income">Income</button></div><label>Amount (₹)<input type="number" id="tx-amount" min="0.01" step="0.01" required/></label><label>Category<select id="tx-category" required>${options}</select></label><label>Date<input type="date" id="tx-date" required/></label><label>Description / Notes<textarea id="tx-description" rows="2" placeholder="Optional"></textarea></label><div class="form-error" id="tx-form-error"></div><div class="modal-actions"><button type="button" class="btn btn-ghost" id="tx-cancel-btn">Cancel</button><button type="submit" class="btn btn-primary" id="tx-submit-btn">Save</button></div></form></div></div>`}
let currentType="expense";
function initTransactionModal({onSaved}={}){const root=document.getElementById("tx-modal-root");if(!root)return null;root.innerHTML=buildModalMarkup();const overlay=document.getElementById("tx-modal-overlay"),form=document.getElementById("tx-form"),errorEl=document.getElementById("tx-form-error"),typeButtons=overlay.querySelectorAll(".type-btn");typeButtons.forEach(btn=>btn.addEventListener("click",()=>{typeButtons.forEach(b=>b.classList.remove("active"));btn.classList.add("active");currentType=btn.dataset.type}));function open(tx=null){errorEl.textContent="";form.reset();document.getElementById("tx-id").value=tx?.id||"";document.getElementById("tx-modal-title").textContent=tx?"Edit Transaction":"Add Transaction";currentType=tx?.type||"expense";typeButtons.forEach(b=>b.classList.toggle("active",b.dataset.type===currentType));document.getElementById("tx-amount").value=tx?.amount??"";document.getElementById("tx-category").value=tx?.category??"Food";document.getElementById("tx-description").value=tx?.description??"";const dateVal=tx?.date?.toDate?tx.date.toDate():new Date();document.getElementById("tx-date").value=dateVal.toISOString().slice(0,10);overlay.classList.add("open")}function close(){overlay.classList.remove("open")}document.getElementById("tx-modal-close").addEventListener("click",close);document.getElementById("tx-cancel-btn").addEventListener("click",close);overlay.addEventListener("click",e=>{if(e.target===overlay)close()});form.addEventListener("submit",async e=>{e.preventDefault();const submitBtn=document.getElementById("tx-submit-btn");submitBtn.disabled=true;submitBtn.textContent="Saving...";try{const payload={type:currentType,amount:document.getElementById("tx-amount").value,category:document.getElementById("tx-category").value,description:document.getElementById("tx-description").value,date:document.getElementById("tx-date").value},id=document.getElementById("tx-id").value;if(id)await updateTransaction(id,payload);else await addTransaction(payload);close();if(onSaved)await onSaved()}catch(err){console.error(err);errorEl.textContent="Could not save transaction. Please try again."}finally{submitBtn.disabled=false;submitBtn.textContent="Save"}});document.querySelectorAll("[data-open-add-modal]").forEach(btn=>btn.addEventListener("click",()=>open(null)));return{open,close}}
export {CATEGORIES,fetchAllTransactions,addTransaction,updateTransaction,deleteTransaction,initTransactionModal};